### ISSUE TITLE
how to stop scrolling when last item visible is the Last Item of the list 

### ISSUE THREAD

**Issue by groomefyvik** [leochuan/CustomLayoutManager#1]
Hi Leochuan 

Can we stop scrolling when last item visible in the screen is the real last item of the  list ?

**Comment by leochuan** [comment]
@groomefyvik

**Comment by leochuan** [comment]
@groomefyvik 

You can edit the getMaxOffsetDegree method. It decides the boundary of last real item which is center of screen by default.

**Comment by abc20899** [comment]
how to scrollToPosition

**Comment by leochuan** [comment]
@abc20899 
You can update to 1.0.2..And call recyclerView's smoothScrollToPosition method
