### ISSUE TITLE
如果需要显示Scrollbars该怎么办？

### ISSUE THREAD

**Issue by zhoubanxian** [leochuan/CustomLayoutManager#4]
你好，我非常喜欢你的项目，有一个小问题，请问能显示Scrollbars吗，特别是在scrollZoomLayoutManager，我该如何操作？

**Comment by leochuan** [comment]
等我下一个更新吧，这要我来处理

**Comment by leochuan** [comment]
@zhoubanxian 等我下一个更新吧，这要我来处理

**Comment by leochuan** [comment]
@zhoubanxian 你拉下新的代码，直接在xml里给recyclerview 设置
```xml
android:scrollbars="horizontal"
```

现在默认scrollbars是平滑滚动的，你如果想不是平滑滚动的话可以调用这个方法
```java
circleLayoutManager.setSmoothScrollbarEnabled(false);
```
